version: 2
jobs:

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run: mdl --style ./.circleci/.mdlrc .

  black:
    docker:
      - image: 667005031541.dkr.ecr.us-west-1.amazonaws.com/black:18.9b0
    steps:
      - checkout
      - run: pyfmt

workflows:
  version: 2
  sdic:
    jobs:
      - mdl
      - black
